
POST http://localhost:3000/auth/v1/login/9866021291

###

POST http://localhost:3000/auth/v1/verify
Content-Type: application/json

{
    "mobileNumber" : "9866021291",
    "password" : "12345"
}

###

POST http://localhost:3000/auth/v1/signup
Content-Type: application/json

{
    "name" : "santosh", 
    "mobileNumber" : "9866021291", 
    "email" : "ssk28411@gmail.com", 
    "password" : "12345"
}
